### ISSUE TITLE
Fix Danny's Movement Code

### ISSUE THREAD

**Issue by LyraStobo** [AdsGames/PeggySim#13]
5 years later it's still a mess.

**Comment by alegemaate** [comment]
LMAO

**Comment by LyraStobo** [comment]
High priority

**Comment by LyraStobo** [comment]
Reopened

**Comment by LyraStobo** [comment]
Is it really shaping up though

**Comment by alegemaate** [comment]
@SullivanStobo any update on this?

**Comment by alegemaate** [comment]
@danwardvs  @SullivanStobo  please, we have a client meeting on Sunday, this has to be in!

**Comment by LyraStobo** [comment]
It's finally fixed!
